### ISSUE TITLE
Can't get the result in German NER ?

### ISSUE THREAD

**Issue by AiHubCN** [thespectrewithin/cross-lingual_NER#7]
hi~, I used your code for cross-Lingual German NER, but I can't get the same result in table1.

In detail, I used fasttext(https://github.com/facebookresearch/fastText/blob/master/docs/crawl-vectors.md) to train bilingual word embeddings by MUSE, I used the same setting as the README.md, and used ./run_lasagne_ncrf.sh to train cross-Lingual NER model. But I get the NER F1 scores just 44 nearly by BWET (id.c.)+self-att and BWET (adv.)+self-att.

Could you give me some advice for getting your result in table1?

**Comment by thespectrewithin** [comment]
I used fasttext trained on Wikipedia (https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md) rather than the crawl vectors for bilingual word embeddings, and to train the ner model i used glove trained with wikipedia and WMT news crawl dataset. In addition, after translation, I added an additional step to capitalize german words based on its stats in Wikipedia (a word is capitalized if the probability that it's capitalized in Wikipedia is greater than 0.6).
